name: ${project.name}
version: ${project.version}
author: U_jun
main: me.ujun.cleanTab.CleanTab
api-version: '1.21'
softdepend:
  - AbsoluteVanish

permissions:
  cleantab.reload:
    default: op

commands:
  cleantab-reload:
    permission: cleantab.reload
    usage: reload tab config