name: SimpleTab
version: ${project.version}
author: U_jun
main: me.ujun.simpletab.SimpleTab
api-version: '1.21'
softdepend:
  - AbsoluteVanish

permissions:
  simpletab.reload:
    default: op

commands:
  simpletab-reload:
    permission: simpletab.reload
    usage: reload simpletab config